package pojo;
// Generated 18/02/2014 21:09:57 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer id;
     private Sucursal sucursal;
     private int legajo;
     private String apellido;
     private String nombre;
     private String cuit;
     private Integer codEmp;
     private String nomEmp;
     private String nomSuc;
     private String convenio;
     private String tarea;
     private Boolean estado;
     private Set<Novedad> novedads = new HashSet<Novedad>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Empleado() {
    }

	
    public Empleado(int legajo, String apellido, String nombre, String cuit, String tarea) {
        this.legajo = legajo;
        this.apellido = apellido;
        this.nombre = nombre;
        this.cuit = cuit;
        this.tarea = tarea;
    }
    public Empleado(Sucursal sucursal, int legajo, String apellido, String nombre, String cuit, Integer codEmp, String nomEmp, String nomSuc, String convenio, String tarea, Boolean estado, Set<Novedad> novedads, Set<Usuario> usuarios) {
       this.sucursal = sucursal;
       this.legajo = legajo;
       this.apellido = apellido;
       this.nombre = nombre;
       this.cuit = cuit;
       this.codEmp = codEmp;
       this.nomEmp = nomEmp;
       this.nomSuc = nomSuc;
       this.convenio = convenio;
       this.tarea = tarea;
       this.estado = estado;
       this.novedads = novedads;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public int getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(int legajo) {
        this.legajo = legajo;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public Integer getCodEmp() {
        return this.codEmp;
    }
    
    public void setCodEmp(Integer codEmp) {
        this.codEmp = codEmp;
    }
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }
    public String getNomSuc() {
        return this.nomSuc;
    }
    
    public void setNomSuc(String nomSuc) {
        this.nomSuc = nomSuc;
    }
    public String getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(String convenio) {
        this.convenio = convenio;
    }
    public String getTarea() {
        return this.tarea;
    }
    
    public void setTarea(String tarea) {
        this.tarea = tarea;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<Novedad> getNovedads() {
        return this.novedads;
    }
    
    public void setNovedads(Set<Novedad> novedads) {
        this.novedads = novedads;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


