package pojo;
// Generated 30/10/2013 11:25:34 by Hibernate Tools 3.2.1.GA



/**
 * Novedad generated by hbm2java
 */
public class Novedad  implements java.io.Serializable {


     private Integer id;
     private Empleado empleado;
     private Concepto concepto;
     private Integer cantidad;
     private String observacion;
     private String fecha;
     private Boolean estado;

    public Novedad() {
    }

	
    public Novedad(Empleado empleado, Concepto concepto) {
        this.empleado = empleado;
        this.concepto = concepto;
    }
    public Novedad(Empleado empleado, Concepto concepto, Integer cantidad, String observacion, String fecha, Boolean estado) {
       this.empleado = empleado;
       this.concepto = concepto;
       this.cantidad = cantidad;
       this.observacion = observacion;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


