package pojo;
// Generated 18/02/2014 21:09:57 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idEmp;
     private Empleado empleado;
     private Integer legajo;
     private String usuario;
     private String clave;
     private String descripcion;
     private String tipo;
     private Boolean estado;
     private Boolean cargo;
     private Date ultimoIngreso;

    public Usuario() {
    }

	
    public Usuario(int idEmp, Empleado empleado, String usuario, String clave, String descripcion, String tipo) {
        this.idEmp = idEmp;
        this.empleado = empleado;
        this.usuario = usuario;
        this.clave = clave;
        this.descripcion = descripcion;
        this.tipo = tipo;
    }
    public Usuario(int idEmp, Empleado empleado, Integer legajo, String usuario, String clave, String descripcion, String tipo, Boolean estado, Boolean cargo, Date ultimoIngreso) {
       this.idEmp = idEmp;
       this.empleado = empleado;
       this.legajo = legajo;
       this.usuario = usuario;
       this.clave = clave;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.estado = estado;
       this.cargo = cargo;
       this.ultimoIngreso = ultimoIngreso;
    }
   
    public int getIdEmp() {
        return this.idEmp;
    }
    
    public void setIdEmp(int idEmp) {
        this.idEmp = idEmp;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Integer getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(Integer legajo) {
        this.legajo = legajo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Boolean getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Boolean cargo) {
        this.cargo = cargo;
    }
    public Date getUltimoIngreso() {
        return this.ultimoIngreso;
    }
    
    public void setUltimoIngreso(Date ultimoIngreso) {
        this.ultimoIngreso = ultimoIngreso;
    }




}


