/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.usuario;


import vistas.empleado.*;
import pojo.Empleado;
import novedades.dao.imp.EmpleadoDaoImp;
import javax.swing.JOptionPane;
import novedades.dao.imp.UsuarioDaoImp;
import org.hibernate.exception.ConstraintViolationException;
import pojo.Usuario;
/**
 *
 * @author Leo
 */
public class AltaUsuario2 extends javax.swing.JDialog {
    
    public static final int GESTOR_EMPLEADO =1;
    private int idEmp = 0;
    private boolean BotonGuardarSelecciono=false;
    
    public boolean isBotonGuardarSelecciono() {
        return BotonGuardarSelecciono;
    }
    /**
     * Creates new form Personal
     */
    
    
    public AltaUsuario2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnEliminar.setVisible(false);
        btnEliminar.setEnabled(false);
        txtId.setVisible(false);
        this.setTitle("NUEVO USUARIO");
        setLocationRelativeTo(this);
        setVisible(true);
        
        // no se realizara la carga de foto
       
        
        
    }
    
    public AltaUsuario2(java.awt.Frame parent, boolean modal,int idEmp) {
        super(parent, modal);
        initComponents();
        this.setTitle("EDITAR EMPLEADO");
        this.idEmp = idEmp;
        btnEliminar.setVisible(true);
        btnBuscar.setVisible(false);
        txtId.setVisible(false);
        Empleado e = new EmpleadoDaoImp().getEmpleado(idEmp);
        Usuario u = new Usuario();
        u.setEmpleado(e);
        configurarParaEditar();
        setLocationRelativeTo(this); 
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        txtLegajo = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtUsuario = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        txtDescripcion = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        labelMetric5 = new org.edisoncor.gui.label.LabelMetric();
        cmbTipo = new org.edisoncor.gui.comboBox.ComboBoxRound();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        panelTranslucidoComplete21 = new org.edisoncor.gui.panel.PanelTranslucidoComplete2();
        btnAtras = new org.edisoncor.gui.button.ButtonIpod();
        btnGuardar = new org.edisoncor.gui.button.ButtonIpod();
        btnEliminar = new org.edisoncor.gui.button.ButtonIpod();
        btnBuscar = new org.edisoncor.gui.button.ButtonIcon();
        txtId = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtClave = new org.edisoncor.gui.passwordField.PasswordFieldRoundIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", 2, 0, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-metallica-2.jpg"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMetric1.setText("LEGAJO");
        panel1.add(labelMetric1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 105, -1, -1));

        txtLegajo.setBackground(new java.awt.Color(255, 255, 0));
        txtLegajo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLegajo.setAnchoDeBorde(1.0F);
        txtLegajo.setColorDeBorde(new java.awt.Color(255, 102, 0));
        txtLegajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLegajoKeyTyped(evt);
            }
        });
        panel1.add(txtLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 104, 100, -1));

        txtUsuario.setBackground(new java.awt.Color(102, 102, 102));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUsuario.setAnchoDeBorde(1.0F);
        txtUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setColorDeBorde(new java.awt.Color(255, 102, 0));
        panel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 142, 152, -1));

        labelMetric2.setText("USUARIO");
        panel1.add(labelMetric2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 143, -1, -1));

        labelMetric3.setText("CLAVE");
        panel1.add(labelMetric3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 219, -1, -1));

        labelMetric4.setText("DESCRIPCION");
        panel1.add(labelMetric4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 181, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDescripcion.setAnchoDeBorde(1.0F);
        txtDescripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColorDeBorde(new java.awt.Color(255, 102, 0));
        panel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 180, 250, -1));

        labelMetric5.setText("TIPO");
        panel1.add(labelMetric5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 258, -1, -1));

        cmbTipo.setBackground(new java.awt.Color(102, 102, 102));
        cmbTipo.setForeground(new java.awt.Color(255, 255, 255));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "ADMINISTRADOR", "COMUN" }));
        cmbTipo.setAnchoDeBorde(2.0F);
        cmbTipo.setColorDeBorde(new java.awt.Color(255, 102, 0));
        panel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 256, 195, -1));

        panelShadow1.setAngle(60.0F);
        panelShadow1.setDistance(10);

        panelTranslucidoComplete21.setColorPrimario(new java.awt.Color(102, 102, 102));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GUARDAR.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Anular");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTranslucidoComplete21Layout = new javax.swing.GroupLayout(panelTranslucidoComplete21);
        panelTranslucidoComplete21.setLayout(panelTranslucidoComplete21Layout);
        panelTranslucidoComplete21Layout.setHorizontalGroup(
            panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTranslucidoComplete21Layout.setVerticalGroup(
            panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTranslucidoComplete21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTranslucidoComplete21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTranslucidoComplete21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTranslucidoComplete21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(panelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 467, -1));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/binoculares.png"))); // NOI18N
        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 32, 58, 58));
        panel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        txtClave.setBackground(new java.awt.Color(102, 102, 102));
        txtClave.setForeground(new java.awt.Color(255, 255, 255));
        txtClave.setAnchoDeBorde(1.0F);
        txtClave.setCaretColor(new java.awt.Color(255, 255, 255));
        txtClave.setColorDeBorde(new java.awt.Color(255, 102, 0));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        panel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 220, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLegajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLegajoKeyTyped
        permitirSoloNumero(evt);
    }//GEN-LAST:event_txtLegajoKeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int resp =JOptionPane.showConfirmDialog(rootPane,"Esta seguro de eliminar el Usuario: \n"+txtUsuario.getText()+" ?", "ELIMINAR USUARIO",JOptionPane.OK_CANCEL_OPTION);
        if (resp==JOptionPane.OK_OPTION) {
            Usuario u = new UsuarioDaoImp().getUsuario(idEmp);
            new UsuarioDaoImp().deleteUsuario(u);
            JOptionPane.showMessageDialog(rootPane, "La Eliminacion se realizo exitosamente ", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        txtLegajo.setEnabled(false);//  esto  es para que no capture el evento foculost de txtlegajo
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{    
            if (idEmp==0){
                Usuario u = new Usuario();
                Empleado e = new EmpleadoDaoImp().getEmpleado(Integer.parseInt(txtId.getText()));
                if(validarEmpleadoNuevo()){
                    u.setEmpleado(e);
                    u = getDatosUsuario();
                    new UsuarioDaoImp().addUsuario(u);
                    JOptionPane.showMessageDialog(rootPane, "SE HA CREADO UN USUARIO EXITOSAMENTE","AVISO",1);
                    this.dispose();
                }
            }else{
                Usuario u = new Usuario();
                Empleado e = new EmpleadoDaoImp().getEmpleado(Integer.parseInt(txtId.getText()));
                if (validarEmpleadoActulizado()){
                    u.setEmpleado(e);
                    u = getDatosUsuario();
                    new UsuarioDaoImp().upDateUsuario(u);
                    JOptionPane.showMessageDialog(rootPane, "SE HA MODIFICADO EL USUARIO EXITOSAMENTE","AVISO",1);
                    this.dispose();
                }
            }
        }catch(ConstraintViolationException cve){
            JOptionPane.showMessageDialog(rootPane, "EL USUARIO YA EXISTE!!!", "AVISO",1);
            txtId.setText("");
            txtUsuario.setText("");
            System.exit(0);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        GestorEmpleado gestor = new GestorEmpleado(null, true, GestorEmpleado.VENTANA_GESTOR_ASISTENCIA);
        if (gestor.isBotonSeleccionado()) {
            
            // si el usuario selecciono un empleado}
            Empleado e = new EmpleadoDaoImp().getEmpleado(gestor.getIdEmp());
            txtLegajo.setText(String.valueOf(e.getLegajo()));
            txtUsuario.setText(e.getNombre().charAt(0)+e.getApellido());
            txtId.setVisible(false);
            txtId.setText(String.valueOf(e.getId()));
            txtDescripcion.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIpod btnAtras;
    private org.edisoncor.gui.button.ButtonIcon btnBuscar;
    private org.edisoncor.gui.button.ButtonIpod btnEliminar;
    private org.edisoncor.gui.button.ButtonIpod btnGuardar;
    private org.edisoncor.gui.comboBox.ComboBoxRound cmbTipo;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric5;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete2 panelTranslucidoComplete21;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundIcon txtClave;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtDescripcion;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtId;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtLegajo;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtUsuario;
    // End of variables declaration//GEN-END:variables


    private void limpiarVentana() {
       txtLegajo.setText("");
       txtUsuario.setText("");
       txtDescripcion.setText("");
       txtClave.setText("");
       cmbTipo.setSelectedIndex(0);
       btnBuscar.requestFocus();
    }
    private void configurarParaEditar() {

        Empleado e = new EmpleadoDaoImp().getEmpleado(idEmp);
        System.out.println("ID "+e.getId());
        Usuario u = new UsuarioDaoImp().getUsuario(e.getId());
        txtLegajo.setText(String.valueOf(e.getLegajo()));
        txtId.setText(String.valueOf(e.getId()));
        txtUsuario.setText(u.getUsuario());
        txtDescripcion.setText(u.getDescripcion());
        txtClave.setText(u.getClave());
        cmbTipo.setSelectedItem(u.getTipo());
        
    }
    
    private void permitirSoloNumero(java.awt.event.KeyEvent evt) {
          // permitir solo el ingreso de numero
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||(caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)){
            evt.consume();  // ignorar el evento de teclado
        }
       
    }
    
    public Usuario getDatosUsuario(){
         Usuario usuario = new Usuario();
         Empleado e = new EmpleadoDaoImp().getEmpleado(Integer.parseInt(txtId.getText()));
         usuario.setEmpleado(e);
         usuario.setLegajo(Integer.parseInt(txtLegajo.getText()));
         usuario.setIdEmp(Integer.parseInt(txtId.getText()));
         usuario.setUsuario(txtUsuario.getText());
         usuario.setDescripcion(txtDescripcion.getText());
         usuario.setClave(txtClave.getText());
         usuario.setTipo(cmbTipo.getSelectedItem().toString());
         usuario.setEstado(true);
         
         return usuario;
     }
    
     public boolean validarEmpleadoActulizado(){
        boolean todoOk=true;
        Empleado empOriginal = new EmpleadoDaoImp().getEmpleado(idEmp); 
        if (empOriginal.getLegajo() !=Integer.parseInt(txtLegajo.getText().trim())) {
             // el empleado modifico el legajo
            Empleado empLeg = new EmpleadoDaoImp().getEmpleado(Integer.parseInt(txtLegajo.getText().trim()));  
             if (empLeg!=null) {
                 todoOk = false;
                 JOptionPane.showMessageDialog(this, "El LEGAJO ya existe");
                 limpiarVentana();
             }
         }
        return todoOk;
     }
     
     public boolean validarEmpleadoNuevo(){
         boolean todoOk = false;
         try{
         Usuario empleado = new UsuarioDaoImp().getUsuario(Integer.parseInt(txtLegajo.getText().trim()));
             //actualizar
             
             if (empleado == null){
                 todoOk= true;
             }else{
                 if (empleado!= null) {
                   JOptionPane.showMessageDialog(this, "El USUARIO ya existe");
                   limpiarVentana();
                } 
             }
           }catch(Exception ex){
              JOptionPane.showMessageDialog(this, "El campo LEGAJO no puede estar vacio");
              todoOk=false;
         }   
         return todoOk;
     }

}
