/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.usuario;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import novedades.dao.imp.ConceptoDaoImp;
import novedades.dao.imp.UsuarioDaoImp;
import pojo.Concepto;
import pojo.Novedad;
import pojo.Usuario;

/**
 *
 * @author Leo
 */
public class Login extends javax.swing.JDialog {
     boolean BotonAceptar= false;
     boolean comun = true;
     boolean ban = true;
     Novedad n = new Novedad();
     Date fecha = new Date();
     SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
     String adm = "ADMINISTRADOR";
     Usuario e;
     Concepto con;
     
    public boolean isBotonAceptar() {
        return BotonAceptar;
    }
    public boolean isComun() {
        return comun;
    }
    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setTitle("LOGIN");
        lblFecha.setText(sdf.format(fecha));
        setLocationRelativeTo(this);
        setVisible(true);
    }
    
    public Login(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        Usuario = new org.edisoncor.gui.label.LabelMetric();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        btnAtras = new org.edisoncor.gui.button.ButtonIpod();
        btnLogin = new org.edisoncor.gui.button.ButtonIpod();
        txtUsuario = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtClave = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        lblFecha = new org.edisoncor.gui.label.LabelMetric();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADMINISTRADOR");
        setIconImage(null);

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "LOGIN", 2, 2, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-metallica-2.jpg"))); // NOI18N

        Usuario.setText("USUARIO");

        labelMetric2.setText("CLAVE");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnAtras.setText("ATRAS");
        btnAtras.setAnimacion(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        btnLogin.setText("ENTRAR");
        btnLogin.setAnimacion(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUsuario.setBackground(new java.awt.Color(102, 102, 102));
        txtUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUsuario.setCaretColor(new java.awt.Color(255, 102, 0));
        txtUsuario.setColorDeBorde(new java.awt.Color(255, 102, 0));
        txtUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        txtClave.setBackground(new java.awt.Color(102, 102, 102));
        txtClave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtClave.setForeground(new java.awt.Color(255, 255, 255));
        txtClave.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClave.setCaretColor(new java.awt.Color(255, 102, 0));
        txtClave.setColorDeBorde(new java.awt.Color(255, 102, 0));
        txtClave.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        lblFecha.setText("30/10/2013");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

    String fecha_login="";
         try{
                // obtengo el usuario que se logueo
             e = new UsuarioDaoImp().getUsuarioAdministrador(txtUsuario.getText(), txtClave.getText());
                // actualizo la ultima fecha de  ingreso del usuario
             e.setUltimoIngreso(new Date());
             new UsuarioDaoImp().upDateUsuario(e);
                //.........
             
             String tipo = e.getTipo();
             if (e!=null) {// si existe el  usuario y es administrador
                 if(tipo.equals(adm)){
                    System.out.println("Es administrador");
                    BotonAceptar=true;
                    comun = false;
                    this.dispose();
                    JOptionPane.showMessageDialog(rootPane, "Bienvenido "+ e.getUsuario());
                 }else if(tipo.equals("COMUN")){
                     if(!fecha_login.equals(sdf.format(fecha))){
                        BotonAceptar = true;
                        comun = true;
//                        con = new ConceptoDaoImp().getConcepto(comun);
                        fecha_login = sdf.format(fecha);//capturo la fecha actual en una cadena
                        System.out.println("Fecha actual "+fecha_login);
                        this.dispose();
                        setearDatos();
                        JOptionPane.showMessageDialog(rootPane, "Bienvenido "+ e.getUsuario());
                     }else{
                         System.out.println("Entro!");
                         BotonAceptar = false;
                         JOptionPane.showMessageDialog(rootPane, "No puede cargar novedades dos veces en el mismo dia, intentalo mañana");
                         this.dispose();
                     }
                   
                     
                  }else {
                    JOptionPane.showMessageDialog(this, "Su Identificacion es Incorrecta, por favor Ingrese de nuevo", "ERROR", JOptionPane.ERROR_MESSAGE);
                    setearDatos();
                    }
                 
            } 
         }catch(java.lang.NumberFormatException edd){
            JOptionPane.showMessageDialog(this, "No pueden estar vacios sus datos de identidad", "Error", JOptionPane.ERROR_MESSAGE);
            setearDatos();
         }catch(java.lang.NullPointerException nul){
             JOptionPane.showMessageDialog(this, "Sus datos son incorrectos, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
             setearDatos();
         }
//        e = new UsuarioDaoImp().getUsuarioLogin(e.getUsuario());
         
}//GEN-LAST:event_btnLoginActionPerformed

private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
     this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_btnAtrasActionPerformed
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt
                        .event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.label.LabelMetric Usuario;
    private org.edisoncor.gui.button.ButtonIpod btnAtras;
    private org.edisoncor.gui.button.ButtonIpod btnLogin;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric lblFecha;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtClave;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void setearDatos() {
       txtUsuario.setText("");
       txtClave.setText("");
       txtUsuario.requestFocus();
    }
    
    
    private void permitirSoloNumero(java.awt.event.KeyEvent evt) {
          // permitir solo el ingreso de numero
         char caracter = evt.getKeyChar();
        if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)){
            evt.consume();  // ignorar el evento de teclado
        }
       
        
    }    
    
    public void capturaUsuario(String user){
        Usuario usr = new UsuarioDaoImp().getUsuarioLogin(user);
        String cadena = String.valueOf(usr.getEmpleado().getLegajo());
//        Empleado emp = new EmpleadoDaoImp().getEmpleado(Integer.parseInt(user));
//        String cadena = emp.getApellido();
//        user = usr.getEmpleado().getNombre().toString()+" "+usr.getEmpleado().getApellido().toString();
        System.out.println("Usuario obtenido: "+usr);
    }

    public Usuario getUsuario() {
        return e;
    }

    public void setUsuario(Usuario usuario) {
        this.e = usuario;
    }

    public Concepto getCon() {
        return con;
    }

    public void setCon(Concepto con) {
        this.con = con;
    }
    
}
